version: '3'
services:
  eureka:
    image: com.demo/eureka
    environment:
        - EUREKA_INSTANCE_PREFERIPADDRESS=true
        - CONFIG_SERVICE_URL=config
    ports:
      - 8761:8761
    networks:
      - backend

  config:
      image: com.demo/config
      environment:
        - SPRING_PROFILES_ACTIVE=docker,native
        - EUREKA_SERVICE_URL=eureka
      ports:
        - 8888:8888
      networks:
        - backend

  admin:
    image: com.demo/admin
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
    ports:
      - 9999:9999
    networks:
      - backend

  dashboard:
    image: com.demo/dashboard
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
    ports:
      - 8788:8788
    networks:
      - backend

  customers:
    image: com.demo/customers
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
    ports:
      - 8080:8080
    networks:
      - backend

  orders:
    image: com.demo/orders
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
    ports:
      - 8081:8081
    networks:
      - backend

  zipkin:
    image: com.demo/zipkin
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    networks:
      - backend

  zuul:
    image: com.demo/zuul
    environment:
      - EUREKA_SERVICE_URL=eureka
      - CONFIG_SERVICE_URL=config
    ports:
      - 9090:9090
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend: