replicaCount: 1

spring:
  profile:
    active: k8s
  application:
    name: admin
    version: 0.0.1

configmap:
  name: admin-application-cm
  volume: admin-application-vol
  deployment: /deployments/config

docker:
  image:
    name: com.demo/admin

container:
  http:
    port: 8080