apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  application.yml: |-
    server.port: {{ .Values.container.http.port }}
    spring.cloud.config.uri: {{ .Values.global.config.service.serviceUrl }}