apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
data:
  application.yml: |-
    eureka:
      client:
        serviceUrl.defaultZone: {{ .Values.global.eureka.service.serviceUrl }}
    server.port: {{ .Values.container.http.port }}