apiVersion: v1
name: netflix-stack
version: 0.0.1
appVersion: 0.0.1
tillerVersion: ">=2.7.2-0"
description: Netflix spring cloud stack
keywords:
  - nextflix
  - stack
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png